apiVersion: v1
kind: Pod
metadata:
  name: nginx-01
  labels:
    podName: nginx-01
    project: example
    appName: example01
    sample/new: demo
    sample.new1: demo1
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-02
  labels:
    podName: nginx-02
    project: example
    appName: example01
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
